language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
install: yarn
deploy:
  provider: script
  skip-cleanup: true
  keep-history: true
  script: ./.travis-deploy.sh
  on:
    branch: master
before_script:
  - "yarn add global gatsby"
  - "yarn"
script:
  - "yarn run test"
after_success:
  - "yarn run deploy"
