language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
install: yarn
deploy:
  provider: script
  skip-cleanup: true
  keep-history: true
  script: bash ./.travis-deploy.sh
  on:
    branch: master
